name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Set up .env file
        run: |
          touch ./backend/avito_shop/.env
          echo '${{ secrets.ENV_FILE }}' > ./backend/avito_shop/.env

      - name: Copy project to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            mkdir -p ~/sos_course_work/backend/avito_shop
          EOF
  
          rsync -az --delete ./backend/avito_shop/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/sos_course_work/backend/avito_shop

      - name: Deploy with Docker Compose
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            cd ~/sos_course_work/backend/avito_shop
            set -a
            source .env
            set +a
            docker compose down
            docker compose up -d --build
          EOF
